### ISSUE TITLE
C# EmbASP Implementation

### ISSUE THREAD

**Issue by neeeeenja** [DeMaCS-UNICAL/EmbASP#48]
Hello, I'm interested in using your implementation as a C# ASP solver. How well does the dev version work for that? Is it still in development?

**Comment by stefanogermano** [comment]
Hi @neeeeenja, please note that _EmbASP_ is not about ASP solving per se; hence, there are no new grounder/solvers based on C# or other languages different from the ones already available elsewhere.

_EmbASP_ is about providing developers with proper means of embedding external reasoning modules (typically relying on declarative formalisms such as ASP or PDDL) into general applications over a range of platform as wide as possible.
It relies on existing solvers and engines (written in any languange), providing an easy way to interact with them.

It is still in development, new implementations have been recently introduced and we are working on providing new releases for all the versions.

Hope this clarifies the issue.
For further information, we suggest to have a look at [the published papers](https://www.mat.unical.it/calimeri/projects/embasp/#Publications).
Feel free to contact us again if we can be of help.
